[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin-contracts=lib/openzeppelin-contracts",
    "@openzeppelin-contracts-07=lib/openzeppelin-contracts-07",
    "@openzeppelin-contracts-08=lib/openzeppelin-contracts-08",
]
fs_permissions = [{ access = 'read-write', path = '/' }]
